version: '3.9'

services:
  # Node.js Application Service
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./login_service/Dockerfile
  #   ports:
  #     - '5000:6000' # Map container port to localhost
  #   environment:
  #     - PORT=6000
  #     - MONGO_URI=mongodb://mongo:27017/userdb
  #     - JWT_SECRET=your_jwt_secret_key
  #     - RABBITMQ_URL=amqp://rabbitmq
  #   depends_on:
  #     - mongo
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #   command: npm run dev

  # MongoDB Service
  mongo:
    image: mongo:6.0.6
    container_name: mongodb
    ports:
      - '27017:27017' # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ service port
      - '15672:15672' # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq # Persist RabbitMQ data

# Volumes for persistent storage
volumes:
  mongo-data:
  rabbitmq-data:
